### ISSUE TITLE
Website: `How to get a Bazel profile`/`Learn more` leads to `404 - Not found`

### ISSUE THREAD

**Issue by rdesgroppes** [EngFlow/bazel_invocation_analyzer#177]
## Description
The `Learn more` link in the `How to get a Bazel profile` section of https://analyzer.engflow.com redirects to a missing documentation page.

### Observed behavior
When clicking on the `Learn more` link under the [How to get a Bazel profile](https://analyzer.engflow.com/#howToGetABazelProfile) section, one is redirected to a [404 - Not found](https://docs.engflow.com/docs/re/faq.html#how-do-i-capture-a-bazel-profile) in the EngFlow Documentation.

### Expected behavior
One should be redirected to an existing documentation page.

### Step-by-step guide on how to reproduce the bug
1. Open https://analyzer.engflow.com
2. Scroll down to the `How to get a Bazel profile` section
3. Click on `Learn more`

### Environment
- Browser: Chromium Version 124.0.6367.207 (Official Build) snap (64-bit)
- Operating System: Ubuntu GNU/Linux 22.04.4 LTS

### Output
![image](https://github.com/EngFlow/bazel_invocation_analyzer/assets/7901596/dccf5844-19ae-4216-890a-6a58aa3d01d4)
![image](https://github.com/EngFlow/bazel_invocation_analyzer/assets/7901596/ae05e1fa-0d30-4f10-8b0d-6be19eacfdf4)

### Further details

**Comment by saraadams** [comment]
Thanks for the report. We'll include the fix on the next update.

**Comment by rdesgroppes** [comment]
@saraadams thank you for the prompt action. I still see:
![image](https://github.com/EngFlow/bazel_invocation_analyzer/assets/7901596/ac3ffa85-64ad-4d78-a190-067fcf4cca9c)
Is it only a matter of deployment time?

**Comment by saraadams** [comment]
> @saraadams thank you for the prompt action. I still see: [...] Is it only a matter of deployment time?

Yes, sorry, this was auto-closed when I merged the fix. I wanted to keep this open until it's deployed, planned for Monday.

**Comment by saraadams** [comment]
Thanks, the fix is live now.
