### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk

### ISSUE THREAD

**Issue by jotadrilo** [EngFlow/bazel_invocation_analyzer#59]
## Description

I have tried a fresh run of the analyzer tool, but it failed with a Java `IllegalArgumentException` exception.

### Observed behavior

The following execution:

```
❯ cd /path/to/bazel/project
❯ bazel build --profile=/tmp/profile.gz //services/...
INFO: Analyzed 167 targets (51 packages loaded, 22200 targets configured).
INFO: Found 167 targets...
INFO: Elapsed time: 16.350s, Critical Path: 9.24s
INFO: 133 processes: 103 internal, 30 darwin-sandbox.
INFO: Build completed successfully, 133 total actions

❯ cd /path/to/bazel_invocation_analyzer
❯ bazel run //cli -- /tmp/profile.gz
```

fails (see output section)

### Expected behavior

I can run this analyzer locally.

### Step-by-step guide on how to reproduce the bug

My local case has been stated above. A similar env var would require further investigation if this is not a known-issue under some weird circunstances.

## Additional context

Supplemental data helps debug issues more quickly and reliably.

Provide as many details as you feel comfortable sharing publicly.
Alternatively, email data to <bazel-invocation-analyzer-dev@engflow.com> while referencing the
created issue, or opt to send the bug report entirely by email.

### Environment

In case it is relevant:

```
❯ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

❯ bazel --version
bazel 5.2.0
```

### Output

```
INFO: Writing tracer profile to '/private/var/tmp/_bazel_jdrios/0ecdd2402f4a3430676f679c51210c11/command.profile.gz'
INFO: Analyzed target //cli:cli (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jdrios/0ecdd2402f4a3430676f679c51210c11/external/bazel_tools/tools/jdk/BUILD:336:14: JavaToolchainCompileBootClasspath external/bazel_tools/tools/jdk/platformclasspath.jar failed: (Exit 1): java failed: error executing command
  (cd /private/var/tmp/_bazel_jdrios/0ecdd2402f4a3430676f679c51210c11/sandbox/darwin-sandbox/13/execroot/com_engflow_bazel_invocation_analyzer && \
  exec env - \
  external/local_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' -cp bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/local_jdk/lib/tools.jar DumpPlatformClassPath bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
# Configuration: 993e48750cca88ecb2670950b516a4e3191944d13a46b2c6270710f1f0943185
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1853)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Target //cli:cli failed to build
INFO: Elapsed time: 0.822s, Critical Path: 0.47s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

### File(s) scanned

NA

### Further details

NA

**Comment by saraadams** [comment]
Can you check whether this still happens now that the Bazel version had been updated? Also, what machine are you on? Looks like a Mac, is it a M1 or M2 MacBook?

**Comment by saraadams** [comment]
Could this be essentially the same issue that's reported in https://github.com/bazelbuild/bazel/issues/15452 ?

**Comment by jotadrilo** [comment]
This is my laptop specs:

* **Version:** 12.3.1 (macOS Monterey)
* **Processor:** Intel Core i9
* **Memory:** 32GB DDR4

I have checked that Bazel is using my local JDK version 11:

```
❯ find bazel-out/ -name 'java'
bazel-out//darwin-fastbuild/bin/cli/cli.runfiles/local_jdk/bin/java
bazel-out//darwin-fastbuild/bin/cli/cli.runfiles/com_engflow_bazel_invocation_analyzer/cli/java
bazel-out//darwin-fastbuild/bin/cli/cli.runfiles/com_engflow_bazel_invocation_analyzer/external/local_jdk/bin/java
bazel-out//darwin-fastbuild/bin/cli/cli.runfiles/com_engflow_bazel_invocation_analyzer/analyzer/java

❯ realpath bazel-out//darwin-fastbuild/bin/cli/cli.runfiles/com_engflow_bazel_invocation_analyzer/external/local_jdk/bin/java
/usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java
```

so let's try to use a different JDK version 11:

```
❯ which java
/usr/local/opt/openjdk@11/bin/java

❯ /usr/local/opt/openjdk@11/bin/java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

❯ sdk install java 11.0.17-librca
❯ sdk use java 11.0.17-librca

❯ java -version
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment (build 11.0.17+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.17+7-LTS, mixed mode)
```

This versions seems to work, although it is failing with my profile:

```
❯ bazel run //cli -- /tmp/profile.gz
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Writing tracer profile to '/private/var/tmp/_bazel_jdrios/0ecdd2402f4a3430676f679c51210c11/command.profile.gz'
INFO: Analyzed target //cli:cli (42 packages loaded, 725 targets configured).
INFO: Found 1 target...
Target //cli:cli up-to-date:
  bazel-bin/cli/cli.jar
  bazel-bin/cli/cli
INFO: Elapsed time: 35.574s, Critical Path: 6.46s
INFO: 34 processes: 4 internal, 14 darwin-sandbox, 16 worker.
INFO: Build completed successfully, 34 total actions
INFO: Build completed successfully, 34 total actions

Bazel Invocation Analyzer by EngFlow

Analyzing /private/tmp/profile.gz
An error occurred while trying to analyze your profile.
Invalid Bazel profile, JSON file missing "Main Thread".

Help improve this tool
You can provide feedback on Bazel Invocation Analyzer as follows:
	https://github.com/EngFlow/bazel_invocation_analyzer/issues to file an issue
	bazel-invocation-analyzer-dev@engflow.com to send us an email
Bazel Invocation Analyzer is open source. We welcome contributions!
```

**Comment by saraadams** [comment]
If I read this correctly, the initial problem has more to do with the Java/Bazel setup than our repo. Note that for the modified run, the JRE you set was ignored:
> WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.

Regarding the analyzer failing on your profile, it outputs:

> Invalid Bazel profile, JSON file missing "Main Thread".

I had thought that all Bazel profiles include a "Main Thread", but perhaps that's not the case.
What kind of command did you run to create the profile?
What does it look like when you open the profile in chrome://tracing?

**Comment by jotadrilo** [comment]
yes, I think these errors are decoupled. Should we open a different issue now?

**Comment by jotadrilo** [comment]
It looks like this:

<img width="1792" alt="Screenshot 2022-10-27 at 11 14 39" src="https://user-images.githubusercontent.com/686015/198244382-c1003a72-6a77-4922-93e2-c21057e8c64f.png">

**Comment by jotadrilo** [comment]
This is a different profile in a repo that implies real compilation, building containers, etc.

<img width="1792" alt="Screenshot 2022-10-27 at 11 17 13" src="https://user-images.githubusercontent.com/686015/198245142-bca06c94-744f-4321-a646-8e325e44b35a.png">

**Comment by jotadrilo** [comment]
I guess the difference is "Main Thread" vs "Service Thread" (no remote execution or similar is used here)

**Comment by jotadrilo** [comment]
BTW, the latter profile is taken from a monorepo with several Go packages, services, and clients plus their associated containers built with Bazel. I was curious about how this analyzer might help there.

**Comment by saraadams** [comment]
> yes, I think these errors are decoupled. Should we open a different issue now?

That makes sense.

**Comment by saraadams** [comment]
> I guess the difference is "Main Thread" vs "Service Thread" (no remote execution or similar is used here)

I don't think it has anything to do with remote execution or not.

From the screenshots it looks like the non-skyframe threads are all named differently.

"action counters:" seems to have the data I expected to be in "action count:".
"cpu counters:" might be the data I usually see in "CPU usage (Bazel):", or maybe although less likely "CPU usage (total):".
"grpc-command-[n]" seems to have the data I expected to be in "Main Thread".
"Service Thread" seems to have the data I expected to be in "Garbage Collector".

I'll have to dig deeper to figure out when which name is used.

**Comment by jotadrilo** [comment]
I will open a new issue describing this issue so you can track any workstream derived from this. Thank you so much!

**Comment by saraadams** [comment]
I have opened #67 just now.
