### ISSUE TITLE
Valid profiles not recognized, e.g. when `Main Thread` is missing

### ISSUE THREAD

**Issue by saraadams** [EngFlow/bazel_invocation_analyzer#67]
## Description

Some valid Bazel profiles are not recognized by the analyzer.
The analyzer checks for specific thread names, which seem to vary more than we check for.

### Observed behavior

Some profiles throw an `InvalidProfileException`, e.g. if no thread named `Main Thread` can be found.

### Expected behavior

All valid Bazel profiles are recognized.

## Additional context

Initially reported in https://github.com/EngFlow/bazel_invocation_analyzer/issues/59 here are some screenshots of valid Bazel profiles with different thread names than the analyzer currently expects:

<img width="1792" alt="Screenshot 2022-10-27 at 11 14 39" src="https://user-images.githubusercontent.com/686015/198244382-c1003a72-6a77-4922-93e2-c21057e8c64f.png">

<img width="1792" alt="Screenshot 2022-10-27 at 11 17 13" src="https://user-images.githubusercontent.com/686015/198245142-bca06c94-744f-4321-a646-8e325e44b35a.png">

### Environment

@jotadrilo reported:
```
❯ bazel --version
bazel 5.2.0
```

> BTW, the latter profile is taken from a monorepo with several Go packages, services, and clients plus their associated containers built with Bazel. I was curious about how this analyzer might help there.

### Output

Optionally include the tool's output. You can add a screenshot, or copy and paste the text output
either in its entirety or only the relevant section(s). Inline the output as a code block here or
attach a text file.

```
❯ bazel run //cli -- /tmp/profile.gz
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Writing tracer profile to '/private/var/tmp/_bazel_jdrios/0ecdd2402f4a3430676f679c51210c11/command.profile.gz'
INFO: Analyzed target //cli:cli (42 packages loaded, 725 targets configured).
INFO: Found 1 target...
Target //cli:cli up-to-date:
  bazel-bin/cli/cli.jar
  bazel-bin/cli/cli
INFO: Elapsed time: 35.574s, Critical Path: 6.46s
INFO: 34 processes: 4 internal, 14 darwin-sandbox, 16 worker.
INFO: Build completed successfully, 34 total actions
INFO: Build completed successfully, 34 total actions

Bazel Invocation Analyzer by EngFlow

Analyzing /private/tmp/profile.gz
An error occurred while trying to analyze your profile.
Invalid Bazel profile, JSON file missing "Main Thread".

Help improve this tool
You can provide feedback on Bazel Invocation Analyzer as follows:
	https://github.com/EngFlow/bazel_invocation_analyzer/issues to file an issue
	bazel-invocation-analyzer-dev@engflow.com to send us an email
Bazel Invocation Analyzer is open source. We welcome contributions!
```

**Comment by saraadams** [comment]
From the screenshots it looks like the non-skyframe threads are all named differently.

"action counters:" seems to have the data I expected to be in "action count:".
"cpu counters:" might be the data I usually see in "CPU usage (Bazel):", or maybe although less likely "CPU usage (total):".
"grpc-command-[n]" seems to have the data I expected to be in "Main Thread".
"Service Thread" seems to have the data I expected to be in "Garbage Collector".

**Comment by jotadrilo** [comment]
I would like to craft a small project in case I can provide a minimal version to reproduce this.

**Comment by saraadams** [comment]
Looking at 
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java
shows that some thread names are hard-coded, in particular ["Critical Path"](https://github.com/bazelbuild/bazel/blob/c9f9b0b84c4863b5b19220679e610efa17e972f0/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L1109)

However, other thread names are [not hard-coded](https://github.com/bazelbuild/bazel/blob/c9f9b0b84c4863b5b19220679e610efa17e972f0/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L1142), but determined by [getReadableName](https://github.com/bazelbuild/bazel/blob/c9f9b0b84c4863b5b19220679e610efa17e972f0/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L1017)
Digging into it, `getReadableName` translates all "grpc-command-[n]" to "Main Thread", and "Service Thread" to "Garbage Collector".

This is a change introduced in https://github.com/bazelbuild/bazel/commit/a03674e6297ed5f6f740889cba8780d7c4ffe05c - so I'm guessing it depends on the Bazel version run to create the profile which thread names we expect to find.

I haven't looked into the counter names yet.

**Comment by saraadams** [comment]
> I would like to craft a small project in case I can provide a minimal version to reproduce this.

My best guess right now is that it depends on the Bazel version these profiles were created with. I understand that you're running Bazel 5.2.0, but can you check what Bazel version created the profiles?

**Comment by jotadrilo** [comment]
Both profiles were crafted using Bazel 4.2.2

**Comment by saraadams** [comment]
Can you check whether you can analyze the profiles with #69?

**Comment by saraadams** [comment]
> I haven't looked into the counter names yet.

Here's where the counter names were changed:
https://github.com/bazelbuild/bazel/commit/ec2eda1b56a5197ee2d019f58d89a68b17974b13#diff-f8db96cce91c612e82faa11be7a835199fd31777cf6bf7ce39a069e140a199b2

**Comment by jotadrilo** [comment]
@saraadams #69 works like a charm!
