### ISSUE TITLE
{short headline describing the requested feature}

### ISSUE THREAD

**Issue by adamlaska** [EngFlow/bazel_invocation_analyzer#86]
## Problem

A clear and concise description of the problem observed.

## (Optional) Preferred solution

A clear and concise description of how the problem might be solved.

This may include

- Implementation details
- Tradeoffs
- Caveats and considerations for future work

## (Optional) Alternative solution

If proposing different solutions, present each one separately.

## Additional information

Supplemental data helps evaluate and implement feature requests more quickly and reliably.

Provide as many details as you feel comfortable sharing publicly.
Alternatively, email data to <analyzer@engflow.com> while referencing the
created issue, or opt to send the feature request entirely by email.

For example, you may want to include example files, reference other issues, etc.

Ideally, do not attach files directly. Bazel profiles can include sensitive data, such as exposing
which dependencies your project includes.

Instead, upload files to the cloud storage provider of your choice and grant appropriate access.
This allows you to adjust who can access them now and in the future. For example, you may want to
remove access to the files once the issue has been resolved.

**Comment by adamlaska** [comment]
> ## Problem
> 
> A clear and concise description of the problem observed.
> 
> ## (Optional) Preferred solution
> 
> A clear and concise description of how the problem might be solved.
> 
> This may include
> 
> - Implementation details
> - Tradeoffs
> - Caveats and considerations for future work
> 
> ## (Optional) Alternative solution
> 
> If proposing different solutions, present each one separately.
> 
> ## Additional information
> 
> Supplemental data helps evaluate and implement feature requests more quickly and reliably.
> 
> Provide as many details as you feel comfortable sharing publicly.
> Alternatively, email data to <analyzer@engflow.com> while referencing the
> created issue, or opt to send the feature request entirely by email.
> 
> For example, you may want to include example files, reference other issues, etc.
> 
> Ideally, do not attach files directly. Bazel profiles can include sensitive data, such as exposing
> which dependencies your project includes.
> 
> Instead, upload files to the cloud storage provider of your choice and grant appropriate access.
> This allows you to adjust who can access them now and in the future. For example, you may want to
> remove access to the files once the issue has been resolved.
>

**Comment by saraadams** [comment]
This seems to be the issue template without any edits / data added. Closing.
