### ISSUE TITLE
{😀/😐/🙁 short headline describing the feedback}

### ISSUE THREAD

**Issue by adamlaska** [EngFlow/bazel_invocation_analyzer#87]
## Feedback

Leave your feedback here.

## Details

Supplemental data gives context for the feedback and makes it easier to act on, where appropriate.

Provide as many details as you feel comfortable sharing publicly.
Alternatively, email data to <analyzer@engflow.com> while referencing the
created issue, or opt to send the feedback entirely by email.

### Output

Optionally include the tool's output. You can add a screenshot, or copy and paste the text output
either in its entirety or only the relevant section(s). Inline the output as a code block here or
attach a text file.

```
example output
```

### File(s) scanned

Optionally attach the Bazel profile(s) that were analyzed by the Bazel Invocation Analyzer.

Ideally, do not attach files directly. Bazel profiles can include sensitive data, such as exposing
which dependencies your project includes.

Instead, upload files to the cloud storage provider of your choice and grant appropriate access.
This allows you to adjust who can access them now and in the future. For example, you may want to
remove access to the files once the issue has been resolved.

### Further details

Provide other data related to this issue that may prove helpful.

**Comment by saraadams** [comment]
This seems to be the issue template without any edits / data added. Closing.
