### ISSUE TITLE
Suggest using skymeld

### ISSUE THREAD

**Issue by saraadams** [EngFlow/bazel_invocation_analyzer#91]
## Problem

Skymeld is a new experimental feature that Bazel users may not be aware of yet.
Include a suggestion to try out skymeld if the profile suggests speed-ups can be expected.

## Suggested solution

* `DataProvider`: detect a drop-off in Bazel CPU usage in the analysis phase
* `SuggestionProvider`: suggest enabling skymeld using [`--experimental_merged_skyframe_analysis_execution`](https://github.com/bazelbuild/bazel/blob/6b21b3b2fb3874d05d08227113c7c740d8bde498/src/main/java/com/google/devtools/build/lib/buildtool/BuildRequestOptions.java#L463)

Also see https://github.com/bazelbuild/bazel/issues/14057

**Comment by lrgoldstein** [comment]
Note, Skymeld currently breaks some of the existing analysis. #97 should really be implemented before suggesting this be turned on.
